### ISSUE TITLE
Identificação de week days

### ISSUE THREAD

**Issue by mobilidados** [ipeaGIT/gtfs2gps#103]
Dependendo do GTFS a forma de identificar week days difere. BH é um exemplo que não o arquivo de calendar e precisa extrair do week day do calendar dates.

**Comment by pedro-andrade-inpe** [comment]
Obrigado pelo feedback, @mobilidados. Vamos corrigir este item após ajustar pendencias relativas à inclusão do pacote no CRAN.

**Comment by pedro-andrade-inpe** [comment]
@mobilidados voce teria um exemplo de arquivo GTFS com o arquivo `calendar_dates`?
