### ISSUE TITLE
consider using geodist for distance calculations

### ISSUE THREAD

**Issue by tbuckl** [ipeaGIT/gtfs2gps#105]
Consider importing the [geodist](https://github.com/hypertidy/geodist) package for the distance calculations [here](https://github.com/ipeaGIT/gtfs2gps/blob/master/src/distance_calcs.cpp#L2-L51).

**Comment by rafapereirabr** [comment]
Hi @tbuckl . Thank you for the suggestion. I don't think using ` geodist ` would be faster than the solution we currently use but I'm happy to see any benchmarks showing otherwise. Have you compared both approaches? What do you think would be the advantages of using  `geodist` here? 
best
Rafa

**Comment by tbuckl** [comment]
Using geodist's implementation of cheap ruler would be faster than using the haversine method. See [here](https://github.com/hypertidy/geodist#performance-comparison) for benchmarks. And using it's implementation of Vincenty may be more accurate in some instances.
