### ISSUE TITLE
sfheaders - revdep check fails

### ISSUE THREAD

**Issue by SymbolixAU** [ipeaGIT/gtfs2gps#107]
I'm (also as @dcooley) making some changes to [`sfheaders`](https://github.com/dcooley/sfheaders/issues/64) and when running a reverse-dependency check I get an error in a couple of your tests.

I think it's because the `/inst/extdata/poa` isn't read correctly

```r
poa <- read_gtfs(system.file("extdata/poa.zip", package = "gtfs2gps"))
```

But wanted to check if you get this error too before I merge my changes to `sfheaders`?

**Comment by rafapereirabr** [comment]
Hi Dave. Thank you for the heads up. The operation `read_gtfs(system.file("extdata/poa.zip", package = "gtfs2gps"))` seems to be working fine in my tests. In any case, please go ahead with the new updates to `sfheaders` and will will adapt our package code accordingly .

**Comment by SymbolixAU** [comment]
Thanks - will do. I've merged some changes into sfheaders master recently, but I don't think anything else breaks.
