### ISSUE TITLE
new function to remove invalid elements of a GTFS file

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [ipeaGIT/gtfs2gps#109]
Implement a function to remove invalid elemengs of a GTFS file. For exampes, trips that do not belong to any shape, or stop_times that do not belong to any trip.

**Comment by pedro-andrade-inpe** [comment]
Add it to read_gtfs through an additional argument, as well as to filter functions.

**Comment by Joaobazzo** [comment]
I've been trying to run some analysis using other gtfs's from cities around the world, and what seems to be happening is that the `gtfs2gps::remove_invalid` function is being very restrictive with some missing information. 13 out of 27 files get reduced by 100%. There's no issue with the function --- just registering it in case we work with these data in the future, so we select `remove_invalid = FALSE`.

See the example
```r
> gtfss <- list.files(path = "../proj_emis_routes/data-raw/gtfs/all/",recursive = TRUE,pattern = "week.gtfs")
> gtfss
 [1] "adelaide/week.gtfs.zip"    "antofagasta/week.gtfs.zip" "athens/week.gtfs.zip"      "belfast/week.gtfs.zip"    
 [5] "berlin/week.gtfs.zip"      "bordeaux/week.gtfs.zip"    "brisbane/week.gtfs.zip"    "canberra/week.gtfs.zip"   
 [9] "detroit/week.gtfs.zip"     "dublin/week.gtfs.zip"      "grenoble/week.gtfs.zip"    "helsinki/week.gtfs.zip"   
[13] "kuopio/week.gtfs.zip"      "lisbon/week.gtfs.zip"      "luxembourg/week.gtfs.zip"  "melbourne/week.gtfs.zip"  
[17] "nantes/week.gtfs.zip"      "palermo/week.gtfs.zip"     "paris/week.gtfs.zip"       "prague/week.gtfs.zip"     
[21] "rennes/week.gtfs.zip"      "rome/week.gtfs.zip"        "sydney/week.gtfs.zip"      "toulouse/week.gtfs.zip"   
[25] "turku/week.gtfs.zip"       "venice/week.gtfs.zip"      "winnipeg/week.gtfs.zip"   
> gtfss_names <- gsub(pattern = "/week.gtfs.zip",replacement = "",x = gtfss)
#
# check old and new sizes
#
> for(i in 1:length(gtfss)){ #  i = 1
  oldfile <- read_gtfs(gtfszip = paste0("../proj_emis_routes/data-raw/gtfs/all/",gtfss[i]), remove_invalid = FALSE)
  newfile <- oldfile %>% gtfs2gps::remove_invalid()
  
  ratio <- as.numeric(object.size(newfile))/as.numeric(object.size(oldfile))
  message(paste0(gtfss_names[i],"-- reduced by = ",100 * round(1-ratio,2)," %"))
}
# adelaide-- reduced by = 1 %
# antofagasta-- reduced by = 0 %
# athens-- reduced by = 100 %
# belfast-- reduced by = 100 %
# berlin-- reduced by = 100 %
# bordeaux-- reduced by = 100 %
# brisbane-- reduced by = 100 %
# canberra-- reduced by = 95 %
# detroit-- reduced by = 100 %
# dublin-- reduced by = 7 %
# grenoble-- reduced by = 16 %
# helsinki-- reduced by = 3 %
# kuopio-- reduced by = 99 %
# lisbon-- reduced by = 100 %
# luxembourg-- reduced by = 100 %
# melbourne-- reduced by = 100 %
# nantes-- reduced by = 1 %
# palermo-- reduced by = 0 %
# paris-- reduced by = 100 %
# prague-- reduced by = 2 %
# rennes-- reduced by = 100 %
# rome-- reduced by = 3 %
# sydney-- reduced by = 10 %
# toulouse-- reduced by = 1 %
# turku-- reduced by = 100 %
# venice-- reduced by = 100 %
# winnipeg-- reduced by = 0 %
```

**Comment by pedro-andrade-inpe** [comment]
The point might be, for instance, if there is no agency then everything will be removed in cascade. @rafapereirabr, should we reopen this issue to check manually if there is some bug in the files that removed 100%?

**Comment by pedro-andrade-inpe** [comment]
@Joaobazzo, thanks for the feedback

**Comment by rafapereirabr** [comment]
@Joaobazzo, thanks for the feedback. I think this situation requires us to take a step back and ask how exactly we expect the `gtfs2gps::remove_invalid` to improve the output our core function. I ask this because most GTFS feeds are somewhat imperfect. However, there are harmless 'imperfections'. 

Think for example of a lonely `stop_id` that is not used in any trip. That would not affect the output of our `gtfs2gps` function. I guess we would need to understand how each 'broken' part of the GTFS feed (e.g. a `trip_id` that is not on `stop_times.txt`, a `shape_id` with no corresponding routes etc) would affect our final output.

**Comment by Joaobazzo** [comment]
I went through each of the 15 problematic GTFS:
- 12/15 had no data.frame of `shapes` associated (so there's nothing we can do) 
- 1/15 had only `NA`s in the `gtfs$routes$agency_id` column (as you mentioned @pedro-andrade-inpe )
- 1/15 had very few `trip_id`s associated with `shape_id`s (trips-shapes relation);  
and few trips-stop_times relation
- 1/15 had few trips-stop_times relation and stop_times-stops relation 

So the main problem seems to be with the data set I'm using, which is not as clean as I thought.

**Comment by rafapereirabr** [comment]
Joao, I just wanted to double check. Are you using the [GTFS feeds from this paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5952869/)? These are the the feeds we are planning to use in the paper

**Comment by Joaobazzo** [comment]
Yeap, thanks for the link @rafapereirabr . We can see that their `shapes.txt` is optional in the paper. Instead, they use another file called `routes.geojson` - in GeoJSON format. See Table 5. These files are available in each city folder, but not in the format we expected. I'll try tomorrow to read them and see how can we incorporate them into our function.

**Comment by rafapereirabr** [comment]
Ok, so it's not as bad as I imagined. You can use the [`geojsonsf` package](https://github.com/SymbolixAU/geojsonsf) to convert between `GeoJSON` and `sf`
