### ISSUE TITLE
departure_times for a given shape_id

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [ipeaGIT/gtfs2gps#110]
It seems that only one `departure_time` is being created for each `shape_id` as output of `gtfs2gps`. Fix it.

**Comment by pedro-andrade-inpe** [comment]
@Joaobazzo, I could not reproduce this problem. Using Porto Alegre data, it seems that everything is working properly. See the figure below:
<img width="580" alt="departure_time" src="https://user-images.githubusercontent.com/8777631/78837483-8cc07800-79ca-11ea-8f1c-f3a23c6ba1e1.png">

**Comment by rafapereirabr** [comment]
The output looks fine in the image above.

**Comment by Joaobazzo** [comment]
Yes, @pedro-andrade-inpe . Now it's working fine (I've submitted the PR #106 to address it). If you run the reproducible example cited on issue #104, you can see that now it generates the correct departure times.

**Comment by rafapereirabr** [comment]
Hmmm. I guess we can close this issue then, correct ?
