### ISSUE TITLE
first point of a GPS trip with distance zero

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [ipeaGIT/gtfs2gps#136]
Change the first point of a trip in GPS data to be zero. Currently it stores the distance between the first and second point. Update all the other points accordingly.

**Comment by rafapereirabr** [comment]
I belive this would simply involve replacing `lead` with `lag` in and then running `new_stoptimes[1, dist := 0]` in the code below. right? I've implemented it in my code and could push the change to the package, but just wanted to make sure this is correct.

```
    # calculate Distance between successive points
    new_stoptimes[, dist := rcpp_distance_haversine(shape_pt_lat, shape_pt_lon, data.table::shift(shape_pt_lat, type = "lag"), data.table::shift(shape_pt_lon, type = "lag"), tolerance = 1e10)]
    new_stoptimes[1, dist := 0]
    new_stoptimes <- na.omit(new_stoptimes, cols = "dist")
```

**Comment by pedro-andrade-inpe** [comment]
I think it is fine. The only concern I have is that, if the only `dist` not `NA` is the first one (that has value zero), possibly it should be removed as well, isn't it?

**Comment by rafapereirabr** [comment]
I thought the idea was to start counting the distance from the first point, so that the distance of point 1 would be zero and not drop any point. Then we continue with the distance  of point 2 (relative to point 1), and distance of ppoint 3 (relative to point 2) and on and on.  right? or maybe I'm confused

**Comment by pedro-andrade-inpe** [comment]
That`s correct. My point is related to the last line of the code above (na.omit). As we force the first point to have dist zero, it will never be NA. If all other dist values are NA, the only remaining point after `na.omit` will be the first point. In this case, should we remove this point as well or keep it?

**Comment by rafapereirabr** [comment]
> That's correct. My point is related to the last line of the code above (na.omit). As we force the first point to have dist zero, it will never be NA. If all other dist values are NA, the only remaining point after `na.omit` will be the first point. In this case, should we remove this point as well or keep it?

Oh, I see what mean. Yes you are right. The data will never have another NA after we force the first point to have dist zero. I think we can drop the line `na.omit(new_stoptimes, cols = "dist")` then.

**Comment by rafapereirabr** [comment]
Oops. I've implemented the solution above and it seems to have broken the speed calculations. I won't have time to dig into this today, so I reversed all lastest related changes. Lesson learned, next time I create a new branch :(
