### ISSUE TITLE
Not filtering for multiple schedules in more complex GTFS feeds

### ISSUE THREAD

**Issue by surgissant** [ipeaGIT/gtfs2gps#141]
I found with the Melbourne GTFS feed that you need to add filtering where there are multiple schedules across different dates, otherwise this code picks up multiple weekday schedules? 

Sorry I don't have time for a reproducible example and I haven't looked into the detail, I can just visually tell that some services are at double normal frequency and can see from the way the code is written it is not looking for schedules on a particular calendar date.

https://transitfeeds.com/p/ptv/497

**Comment by rafapereirabr** [comment]
Hi Belinda. Thank you for opening this issue.

You're right, the current version of `gtfs2gps` does not allow one to select services at an specific date. It does have a `filter_week_days` function that allows one to subset services on business days, though.  Here is how it works:

```
library(gtfs2gps)

# read gtfs
poa <- read_gtfs(system.file("extdata/poa.zip", package = "gtfs2gps"))

# keep only business days
poa_bd <- filter_week_days(poa)

# convert to 'gps' format
poa_bd_gps <- gtfs2gps(poa_bd)

```

Do you think that would address your question?

**Comment by surgissant** [comment]
Hi, thanks, no I am aware that it filters for weekdays, but it isn't looking into the calendar to just pick up one schedule, it would almost make more sense to just pick one date to run as I assume a lot of bigger feeds would have different schedules on different weekdays (we tend to have a slightly different Friday timetable in our services to the rest of the week, but also I probably ran the code over a time period where there was a timetable change or a works alternative timetable within the dates covered by the GTFS file).

I can post further detail when (if!) I have time to look into specifics.

**Comment by surgissant** [comment]
https://openmobilitydata-data.s3-us-west-1.amazonaws.com/public/feeds/ptv/497/20200807/original/calendar.txt

You can see by the patterns in this file (although this is across 4+ modes run by many operators) that services don't run uniformly across the working week, so it doesn't make sense to visualise an aggregate of working days across the same time of day.

**Comment by rafapereirabr** [comment]
Hi Belinda.

With the latest pull request, the `gtfs2gps` package now has a `{filter_by_day}` function that allows users to filter services on specific week days. 

```
library(gtfs2gps)

# read gtfs feed
poa <- read_gtfs(system.file("extdata/poa.zip", package = "gtfs2gps"))
 
# filter services on Wed and Fri
subset <- filter_by_day(poa, c("wednesday", "friday"))
```
