### ISSUE TITLE
filter_day_period

### ISSUE THREAD

**Issue by Joaobazzo** [ipeaGIT/gtfs2gps#147]
`filter_day_period` function is also filtering by `agency_id` - and I think it's being too restrictive. Perhaps we could avoid using it since some gtfs's has NA's in gtfs$routes$agency_id. We could filter only by the most important groups (shapes/trips/stop_times/routes/stops), as we do in `filter_by_shape_id` function

**Comment by pedro-andrade-inpe** [comment]
The only thing it does with agency is to filter itself:

```R
  gtfs$agency <- gtfs$agency[ agency_id %chin% unique(gtfs$routes$agency_id) ]
```

Perhaps you are calling `remove_invalid()` afterwards?

**Comment by Joaobazzo** [comment]
Exactly @pedro-andrade-inpe . The issue is with this line you mentioned. 
```
> unique(gtfs$routes$agency_id)
[1] NA
```
Particularly for the city of Detroit (in case you want to see its [GTFS](https://transitfeeds.com/p/detroit-department-of-transportation/299). I wasn't calling `remove_invalid()`.

**Comment by pedro-andrade-inpe** [comment]
@Joaobazzo is the solution below ok for you?

The idea is to replace

```R
  if(!is.null(gtfs$agency))
    gtfs$agency <- gtfs$agency[ agency_id %chin% unique(gtfs$routes$agency_id) ]
```

by aditionally checking whether routes have agency_ids:

```R
  if(!is.null(gtfs$agency) && !is.null(unique(gtfs$routes$agency_id)))
    gtfs$agency <- gtfs$agency[ agency_id %chin% unique(gtfs$routes$agency_id) ]
```

I would prefer to do this instead of removing the filter in order to keep compatibility with possible codes of other users that work properly using this function.

**Comment by Joaobazzo** [comment]
I think this solution looks good!
