### ISSUE TITLE
Improve gps_as_sflinestring peformance with  gm_geometries{geometries} 

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/gtfs2gps#157]
@Joaobazzo suggested we could perhaps get major performance improvements in `gps_as_sflinestring` if we used the gm_geometries{geometries} function. [Demo here](https://twitter.com/_davecooley/status/1282159034238296065).

**Comment by pedro-andrade-inpe** [comment]
Duplicated #143
