### ISSUE TITLE
function to split a GTFS file

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [ipeaGIT/gtfs2gps#163]
Some GTFS files might be larger than the available memory. Implement a function to split a GTFS file into several smaller GTFS files by separating their shape ids.

**Comment by rafapereirabr** [comment]
The `gtfs2gps` package already can handle really large GTFS feeds when the user sets the `filepath` in the  `gtfs2gps()` function [*]. So I'm not sure we need this function.

[*] We should probably make this clearer in the documenation. Something like: "Setting a `filepath` allows the user to process a large GTFS feed and save a larger than memory GPS-like table."
