### ISSUE TITLE
availableCores() - 1 => max(1, availableCores() - 1)

### ISSUE THREAD

**Issue by HenrikBengtsson** [ipeaGIT/gtfs2gps#164]
Hi, I spotted that you use `availableCores() - 1` in:

https://github.com/ipeaGIT/gtfs2gps/blob/0415d9ac4ce2d35dfe629efffcfb668b691ddb06/R/gtfs2gps.R#L232-L236

Note that this might return `0` because `availableCores()` returns a positive integer equal or greater to one.

To avoid ending up with zero cores, use:

```r
cores <- max(1, availableCores() - 1)
```

PS. I found this bug from running revdep checks on **progressr**, cf. https://github.com/HenrikBengtsson/progressr/blob/develop/revdep/problems.md#gtfs2gps

**Comment by HenrikBengtsson** [comment]
Correction: It should be `max()` and nothing else.

**Comment by pedro-andrade-inpe** [comment]
Many thanks for the feedback, @HenrikBengtsson. We will apply this change to the next release.
