### ISSUE TITLE
export output of gtfs2gps to .rds format?

### ISSUE THREAD

**Issue by Joaobazzo** [ipeaGIT/gtfs2gps#178]
I'm wondering if it's worth to have an option on `gtfs2gps::gtfs2gps` that exports to `.rds` data, so we could compress the data. I'm still not sure about it. For instance, São Paulo GTFS (emtu+sptrans, filtered by `shape_id`'s that is inside or crosses SP border), we've got 17,1 Gb of GPS data.

**Comment by rafapereirabr** [comment]
This would only make a difference if the user also passes a `filepath` parameter. Right? It would be a simple change to the function, but it would probably require that we use `write_rds{readr}` to save the output more efficiently.

**Comment by Joaobazzo** [comment]
Yeap, it makes a difference only when `filepath` is used. Perhaps it would require an extra argument, such as `compress = TRUE`, and a dependency of `readr` package.

**Comment by pedro-andrade-inpe** [comment]
We do not have many dependencies in the package, so it seems reasonable to have this argument to save memory and speedup loading the data as well.

**Comment by pedro-andrade-inpe** [comment]
`readr::write_rds()` has argument `compress = c("none", "gz", "bz2", "xz")`. Which value should we use?

**Comment by rafapereirabr** [comment]
`compress = "gz"` is faster and more effective.
