### ISSUE TITLE
gps connecting last stop_id to first

### ISSUE THREAD

**Issue by Joaobazzo** [ipeaGIT/gtfs2gps#181]
Problem with specific shape_id of Porto Alegre GTFS ([link](https://www.dropbox.com/s/2tw4hxco7htw8a1/bra_poa.zip?dl=0)). 

It seems that the last stop_id is connecting to the first one.

```r
gps_point <- gtfs2gps::read_gtfs("../data-raw/gtfs/bra_poa/bra_poa.zip") %>% 
  gtfs2gps::filter_by_shape_id("A19-1") %>%
  gtfs2gps::filter_single_trip() %>% 
  gtfs2gps::gtfs2gps() 

gps_headrs <- gps_point %>%
  sfheaders::sf_linestring(x = "shape_pt_lon", 
                           y = "shape_pt_lat", 
                           linestring_id = "trip_id") %>% 
  sf::st_as_sf() %>% 
  sf::st_set_crs(4326)


mapview::mapview(gps_headrs$geometry)
```
![image](https://user-images.githubusercontent.com/23303664/110335214-5fc57c80-8002-11eb-97ab-c1a5413aeae9.png)

I'm still trying to figure out what's happening. If I find anything I'll share here.

**Comment by Joaobazzo** [comment]
I think it's a problem with `shape_id` data. I'm not sure if there something we can do.

```r
# read
gps_point <- gtfs2gps::read_gtfs("../data-raw/gtfs/bra_poa/bra_poa.zip") %>% 
  gtfs2gps::filter_by_shape_id("A19-1")
# shape
gps_shape <- sfheaders::sf_multipoint(gps_point$shapes,
                                      x = 'shape_pt_lon',
                                      y = 'shape_pt_lat') %>% 
  sf::st_as_sf() %>% sf::st_set_crs(4326)
# stop
gps_stop <- sfheaders::sf_multipoint(gps_point$stops,
                                      x = 'stop_lon',
                                      y = 'stop_lat') %>% 
  sf::st_as_sf() %>% sf::st_set_crs(4326)
# view
mapview(gps_stop$geometry)
mapview(gps_shape$geometry)
``` 
This is our `stops` file. Seems right.
![image](https://user-images.githubusercontent.com/23303664/110339327-d06e9800-8006-11eb-9f05-25bc691f728a.png)

however, this is our `shapes` file. there are three points in the middle of nowhere

![image](https://user-images.githubusercontent.com/23303664/110339442-f005c080-8006-11eb-83a5-e665cc36c91f.png)

I'm thinking of simply manually exclude those very distance points.

**Comment by rafapereirabr** [comment]
Hm... yep. This seems to be an error with the GTFS Feed. Nothing really the package could do about. I agree the best approach to this would be to manually exclude those points.
