### ISSUE TITLE
Build pkgdown website with github actions

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/gtfs2gps#188]
I've tried to add a github action to build our pkgdown website.... but it's not working :( 

Help!

**Comment by pedro-andrade-inpe** [comment]
@rafapereirabr, I'm not familiar with `pkgdown` but as far as I know, the webpage is stored in `docs` directory within GitHub. This would require a robot to open a pull request with the updated version of the webpage. Is there any alternative for this?

**Comment by rafapereirabr** [comment]
Perhaps @dhersz could give us a hand?

**Comment by rafapereirabr** [comment]
Apparently it's still not working

**Comment by dhersz** [comment]
https://ipeagit.github.io/gtfs2gps/ looks fine to me.

**Comment by rafapereirabr** [comment]
it seems Ok, but it is not updating the changelog according to the `NEWS.md` file.

**Comment by dhersz** [comment]
Probably related to https://github.com/r-lib/pkgdown/issues/1947

**Comment by rafapereirabr** [comment]
Fixed
