### ISSUE TITLE
Make time operations using data.table::as.ITime

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/gtfs2gps#2]
Time operations are currently performed using `fasttime::fastPOSIXct`. Replacing this with `data.table::as.ITime` should make the code faster and reduce package depencies

**Comment by pedro-andrade-inpe** [comment]
`fasttime::fastPOSIXct` is used basically to convert `stoptimes$departure_time`, like:

```R
stoptimes_temp[, departure_time := as.POSIXct(departure_time, format="%H:%M:%OS")]
```

would it be better to implement this conversion directly in `read_gtfs()`?

**Comment by rafapereirabr** [comment]
I don't see strong reasons to make this transformation in one function or in the other, really. I'm glad to keep it as it is but I wouldn't opposing moving it to `read_gtfs()`.

The important change here, I believe, would be to use the `as.ITime`, which is native to `data.table` . It should probably be faster and would remove the dependency on the `fasttime` package

**Comment by pedro-andrade-inpe** [comment]
I tried to move this conversion to `load_gtfs` and one of my test scripts stopped with a strange error. According to the documentation, "`as.ITime` does not allow days longer than 24 hours". When I convert Sao Paulo's `stop_times` using `as.ITime`, it produces NA values for times after 24 hours. See below:

```
12: T2-1@1#2310     23:10:00       23:10:00    3609             1
13: T2-1@1#2310     24:02:00       24:02:00    1456            62
14: T2-1@1#2332     23:32:00       23:32:00    3609             1
15: T2-1@1#2332     24:24:00       24:24:00    1456            62
16: T2-1@1#2357     23:57:00       23:57:00    3609             1
17: T2-1@1#2357     24:49:00       24:49:00    1456            62
18:  T2-1@2#520     05:20:00       05:20:00    3609             1
```

is converted to

```
12: T2-1@1#2310     23:10:00       23:10:00    3609             1
13: T2-1@1#2310         <NA>           <NA>    1456            62
14: T2-1@1#2332     23:32:00       23:32:00    3609             1
15: T2-1@1#2332         <NA>           <NA>    1456            62
16: T2-1@1#2357     23:57:00       23:57:00    3609             1
17: T2-1@1#2357         <NA>           <NA>    1456            62
18:  T2-1@2#520     05:20:00       05:20:00    3609             1
```

The same happens with Porto Alegre data. To avoid such NA values in the processing scripts, I will replace `"24:"` by `"00:"` and then execute this conversion within  `load_gtfs`.
