### ISSUE TITLE
`read_gtfs` does not load `route_*_name` in `$routes`

### ISSUE THREAD

**Issue by cseveren** [ipeaGIT/gtfs2gps#212]
The `read_gtfs` command does not load `route_long_name` and/or `route_short_name` into the `$routes` files. One or both of these are required according to GTFS spec, and this causes errors in feed validation using [google/transitfeed](https://github.com/google/transitfeed). Omitting these fields may cause downstream issues when using `read_gtfs` and `gtfs2gps` to convert from frequency-based GTFS spec to standard stop-time based spec (e.g., https://github.com/ipeaGIT/r5r/issues/181).

Simple to fix: Replace
https://github.com/ipeaGIT/gtfs2gps/blob/33689106dccfd05ecb44ee1982fbf858ed7e2717/R/read_gtfs.R#L23
with
```
routes = c("agency_id", "route_id", "route_type", "route_short_name", "route_long_name"),
```

Thanks!

**Comment by rafapereirabr** [comment]
Hi @cseveren . Thank you for opening the issue. Our `read_gtfs()` function is a wrapper around the `gtfsio::import_gtfs()` function. So, in principle, this should be relatively simple to solve by adding a `...` parameter inside the `read_gtfs()` function. This way, the user can select columns following the parameters of `gtfsio::import_gtfs()`.

An important detail here is that some GTFS columns are required for the operations we run in `gtfs2gps` (see them below). 

```
    gtfsio::import_gtfs(
      path = gtfszip,
      quiet = quiet,
      # files = c("agency", "routes", "stops", "stop_times", "shapes", "trips", "calendar", "calendar_dates", "frequencies"),
      fields = list(
        routes = c("agency_id", "route_id", "route_type"),
        #stops = c("stop_id", "stop_lat", "stop_lon"),
        stop_times = c("trip_id", "arrival_time", "departure_time", "stop_id", "stop_sequence"),
        shapes = c("shape_id", "shape_pt_lat", "shape_pt_lon", "shape_pt_sequence"),
        trips = c("route_id", "service_id", "trip_id", "shape_id")
      )
    )
```

**Comment by cseveren** [comment]
Yes, it should. Thanks.

**Comment by rafapereirabr** [comment]
Great. With the latest changes to the package, our read and write functions keep the `route_short_name` and `route_long_name` columns by default. Closing this issue for now.
