### ISSUE TITLE
Issues with the upcoming release of units 0.8-0

### ISSUE THREAD

**Issue by Enchufa2** [ipeaGIT/gtfs2gps#224]
Dear maintainer,

We are preparing units 0.8-0 for release in approximately a month. I'm writing to you because our revdep checks report new issues in your package with this new version (you can check them [here](https://github.com/r-quantities/units/blob/main/revdep/problems.md#gtfs2gps)).

These issues seem to be caused by an incorrect comparison of units and numeric vectors using `all.equal()` (or `expect_equal()`, which uses the former). The new version of units includes a fix in the `all.equal.units()` method that (correctly) triggers these errors.

To address this, I suggest to either drop the units of the first member of such comparisons, or to promote the second member to a units object with proper units.

**Comment by pedro-andrade-inpe** [comment]
Thanks @Enchufa2, we will fix this soon.
