### ISSUE TITLE
gtfs2gps::gtfs2gps not processing transport network sf object

### ISSUE THREAD

**Issue by argunaw** [ipeaGIT/gtfs2gps#240]
The code I'm running is based on this post:

[https://urbandemographics.blogspot.com/2020/03/creating-animated-gif-of-public.html](url)

I ran the following code and received a message that 0 of 92 trips were processed correctly:

# load libraries
`library(gtfs2gps)`
`library(ggplot2)`
`library(gganimate)`
`library(data.table)`
`library(ggthemes)`
`library(sf)`
`library(viridis)`
`library(sfheaders)`

#### get local GTFS.zip file
`gtfs_zip <- system.file("extdata/saopaulo.zip", package="gtfs2gps" )`

#### read gtfs
`gtfs_dt <- gtfs2gps::read_gtfs(gtfs_zip)`

#### filter transport services on weekdays
`gtfs_dt <- gtfs2gps::filter_week_days(gtfs_dt)`

#### get transport network as sf object
`shapes_sf <- gtfs2gps::gtfs_shapes_as_sf(gtfs_dt)`

#### Convert GTFS data into a data.table with GPS-like records
`gps_dt <- gtfs2gps::gtfs2gps(gtfs_dt, spatial_resolution = 30, parallel = T)`

Am I missing something here? The code is effectively copied and pasted from the link, except I removed progress=T from the final command because it gave me an error messsage.

**Comment by Joaobazzo** [comment]
Thanks for bringing this issue @argunaw . In fact, this is something we are working to fix in the `gtfs2gps` package.
For now, one way to get around is to use alternative functions from `gtfstools` package and to convert frequency-type-gtfs to time-table (through `gtfstools::frequencies_to_stop_times()` function). I made some other adjustments to run more quickly the example
See the reprex below
```r

# load libraries
library(gtfs2gps)# devtools::install_github("ipeaGIT/gtfs2gps") 
library(gtfstools)# devtools::install_github("ipeaGIT/gtfstools") 
library(geobr)
library(ggplot2)
library(gganimate)
library(data.table)
library(ggthemes)
library(sf)
library(viridis)
library(sfheaders)



###### 1. process public transport data  ------------------

# get local GTFS.zip file
gtfs_zip <- system.file("extdata/saopaulo.zip", package="gtfs2gps" )

# read gtfs
gtfs_dt <- gtfstools::read_gtfs(gtfs_zip)

# filter transport services on weekdays
gtfs_dt <- gtfs2gps::filter_week_days(gtfs_dt)

# filter by shape_id
gtfs_dt <- gtfs2gps::filter_by_shape_id(gtfs_dt,shape_ids = "52857")

# get transport network as sf object
shapes_sf <- gtfs2gps::gtfs_shapes_as_sf(gtfs_dt)

# convert frequency to stop_times
gtfs_dt <- gtfstools::frequencies_to_stop_times(gtfs = gtfs_dt)

gtfs_dt$stop_times[,arrival_time := data.table::as.ITime(arrival_time)]
gtfs_dt$stop_times[,departure_time := data.table::as.ITime(departure_time)]

# eliminating NA stop_time
#gtfs_dt$stop_times <- gtfs_dt$stop_times[!is.na(arrival_time)]

# filter by single trip
gtfs_dt <- gtfs2gps::filter_single_trip(gtfs_data = gtfs_dt)


# Convert GTFS data into a data.table with GPS-like records
#future::plan(workers = 19,strategy = "multisession")

gps_dt <- gtfs2gps::gtfs2gps(gtfs_dt)
head(gps_dt)
tail(gps_dt)
```
Here is the plotting of gif

```r

# remove observations with 'too low speed' (in km/h)
gps_dt2 <- gps_dt[as.numeric(speed) > 1 , ]



# Convert "GPS" points into sf
gps_sf <- sfheaders::sf_point(gps_dt2, x = "shape_pt_lon" , y = "shape_pt_lat", keep = T)
sf::st_crs(gps_sf) <- 4326
head(gps_sf)

###### 2. gif with blank background [fully reproducible] ------------------

# download Sao Paulo border for spatial context
sao_paulo <- geobr::read_municipality(code_muni = 3550308)

anim <- ggplot() +
  #geom_sf(data = sao_paulo, color='gray50', fill=NA) +
  geom_sf(data = shapes_sf, color='gray90', size=0.01) +
  geom_point(data = gps_dt2, aes(x = shape_pt_lon
                                 , y=shape_pt_lat, colour = trip_id)
             , size=1.5, alpha = 0.5, show.legend = FALSE) +
  scale_colour_viridis( discrete = T ) +
  coord_sf(ylim = c(min(gps_dt2$shape_pt_lat), max(gps_dt2$shape_pt_lat)) ) +
  theme_map() +
  
  # gganimate specificatons
  labs(title = 'Time: {frame_time}') +
  transition_time(as.POSIXct(timestamp) + 10800) +  # need to fix issue with time zone
  shadow_wake(wake_length = 0.015, alpha = FALSE) +
  ease_aes('linear')


# save gif
anim_save(animation = anim, "spo_gtfs_sample_20fps__GIST.gif", fps = 20)


```
![spo_gtfs_sample_20fps__GIST](https://user-images.githubusercontent.com/23303664/157519732-16979f67-91ea-4d5e-ac1c-4fa1e71b4478.gif)


Let us know if this worked for you!

**Comment by argunaw** [comment]
Thank you for the response, this worked for me for the data you posted. I tried this with the NYC gtfs data, downloaded from here:

[](https://transitfeeds.com/p/mta/79)

Unfortunately the NYC data doesn't have the frequencies.txt file in their data. I'll await the package update for the gtfs2gps::gtfs2gps command for the NYC data. Thanks again for posting the existing workaround for other datasets with the frequencies data!

**Comment by Joaobazzo** [comment]
Hi @argunaw .
If NYC doesn't have frequencies data, what you could do is basically skip the conversion step

```r
# convert frequency to stop_times
gtfs_dt <- gtfstools::frequencies_to_stop_times(gtfs = gtfs_dt)

gtfs_dt$stop_times[,arrival_time := data.table::as.ITime(arrival_time)]
gtfs_dt$stop_times[,departure_time := data.table::as.ITime(departure_time)]
```

I downloaded the NYC gtfs and apparently I couldn't see anything wrong. If you can provide a reproducible example on this specific issue of NYC it would be great.

```R
gtfs_ny <- read_gtfs("../../Downloads/gtfs.zip")

gtfs_ny <- gtfs_ny %>% 
  filter_by_shape_id("1..N03R") %>% 
  filter_single_trip()

gps_ny <- gtfs2gps(gtfs_ny)

gps_ny
gps_ny <- gps_ny[as.numeric(speed) > 1 , ]



# Convert "GPS" points into sf
gps_sf <- sfheaders::sf_point(gps_ny
                              , x = "shape_pt_lon"
                              , y = "shape_pt_lat"
                              , keep = T)
sf::st_crs(gps_sf) <- 4326
head(gps_sf)

ggplot() +
  geom_sf(data = gps_sf, color='yellow', size=5) +
  geom_point(data = gps_ny, aes(x = shape_pt_lon
                                 , y=shape_pt_lat, colour = trip_id)
             , size=1.5, alpha = 0.5, show.legend = FALSE) +
  scale_colour_viridis( discrete = T ) +
  coord_sf(ylim = c(min(gps_ny$shape_pt_lat), max(gps_ny$shape_pt_lat)) ) +
  theme_map() +
  
  # gganimate specificatons
  labs(title = 'Time: {frame_time}') +
  transition_time(as.POSIXct(timestamp) + 10800) +  # need to fix issue with time zone
  shadow_wake(wake_length = 0.015, alpha = FALSE) +
  ease_aes('linear')
![nyc](https://user-images.githubusercontent.com/23303664/163061785-185218b6-6e0a-49b3-ab14-6fe5df841c48.gif)

```
![nyc](https://user-images.githubusercontent.com/23303664/163061785-185218b6-6e0a-49b3-ab14-6fe5df841c48.gif)

**Comment by argunaw** [comment]
Hi @Joaobazzo I tried running your code and got an error message.

Here is the code I ran after downloading NYC gtfs data from the following link: [https://transitfeeds.com/p/mta/79](https://transitfeeds.com/p/mta/79).


```
# load libraries
library(gtfs2gps)
library(ggplot2)
library(gganimate)
library(data.table)
library(ggthemes)
library(sf)
library(viridis)
library(sfheaders)
library(gtfstools)

### read in gtfs data
nyc <- read_gtfs("......Documents/gtfs.zip")

gtfs_ny <- nyc %>% 
  filter_by_shape_id("1..N03R") %>% 
  filter_single_trip()

###gps - this is where my code fails and returns a null dataset
gps_ny <- gtfs2gps(nyc_real)

```

Here is the error message I get when I run the gtfs2gps function:

```
The following object is masked from ‘package:purrr’:

    set_names

udunits database from ....../R/win-library/4.1/units/share/udunits/udunits2.xml
Trip 'AFA21GEN-1037-Sunday-00_007200_1..N03R' has less than two stop_ids. Ignoring it.
Shape '1..N03R' has no departure_time. Ignoring it.
0 out of 1 shapes (0%) were properly processed.
0 out of 1 trips (0%) were properly processed.
Warning messages:
1: In eval(jsub, SDenv, parent.frame()) : NAs introduced by coercion
2: In eval(jsub, SDenv, parent.frame()) : NAs introduced by coercion
```

I'm using gtfs2gps package version 2.0.1. Let me know if there's any other information I can provide.

**Comment by Joaobazzo** [comment]
Hi @argunaw. I'm closing this issue for now. If there's any other questions with the GIF plot or with the `gtfs2gps` function, please let us know.
