### ISSUE TITLE
Vignette link does not work

### ISSUE THREAD

**Issue by williamlai2** [ipeaGIT/gtfs2gps#246]
Vignette link on this page: https://ipeagit.github.io/gtfs2gps/ leads to https://github.com/ipeaGIT/gtfs2gps/blob/master/vignettes/intro_to_gtfs2gps.md but that does not exist in the repo. The `.Rmd` file does exist though.

**Comment by rafapereirabr** [comment]
thank you for the heads up. I've just fixed the link.
