### ISSUE TITLE
Issues with the upcoming release of units 0.8-2

### ISSUE THREAD

**Issue by Enchufa2** [ipeaGIT/gtfs2gps#272]
Dear maintainer,

We are preparing units 0.8-2 for release. I'm writing to you because our revdep checks report new issues in your package with this new version (you can check them [here](https://github.com/r-quantities/units/blob/main/revdep/problems.md#gtfs2gps)).

These issues are caused by the latest fixes in the comparison operators for units. Comparing quantities usually involves converting between compatible units, and these conversions are managed by the underlying udunits2 library with float precision. Therefore, to prevent repoting as _different_ units that are indeed equal (e.g. 3.6 km/h == 1 m/s), the new patch release improves this by comparing with some tolerance.

In your package, the failure linked above is caused by a dataframe filtering based on units, and some of them are below this tolerance value. To fix this and keep compatibility with the old and new version of units, my recommendation is to avoid tests relying on the remaining number of rows after filtering.

**Comment by rafapereirabr** [comment]
Thanks for the heads up. We're looking into this.
