### ISSUE TITLE
Merge `gtfs2gps_dt` scripts into a single function

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/gtfs2gps#3]
The scripts `gtfs2gps_dt_parallel.R` and `gtfs2gps_dt_parallel_freq.R` basically do the same thing. Both convert a GTFS feed to a "GPS format". The difference is that the former works on a standard GTFS feed, while the latter works on a frequency-based GTFS. Ideally, both functions shuld be combined into a single function.
- alert: this would require a method to automatically identify the type of GTFS passed as input to the function.

**Comment by rafapereirabr** [comment]
Hi Joao. I've created the function `test_gtfs_freq.R` to test whether a GTFS feed is frequency based or whether it's a simple feed with a detailed `stop_times.txt` file. This should help solving this issue

**Comment by Joaobazzo** [comment]
After merge the functions:
> check length units throughout the function, we keep converting "km" to "m" and vice-versa

**Comment by Joaobazzo** [comment]
There are basically two scripts,`gtfs2gps_single_dt.R` and `mod_updates.R`, which will be pulled today @pedro-andrade-inpe . Here's the approach

##### `gtfs2gps_single_dt.R`
> **gtfs2gps_dt_single <- **function**(gtfszip, filepath, spatial_resolution = 15, week_days = TRUE){**
>  _- 1) read GTFS_
> _- 2) convert into sf object_
> _`# Core function`_
>> **corefun <- **function**(shapeid){** 
>>_- 3) spatial interpolation_
>> _`# test data type`_
>>> **if(test_gtfs_freq(gtfs_data)=="frequency"){**
>>> _- 4.1) update newstoptimes based on `update_freq(all_tripids)`_
>>> **else**
>>> _- 4.2) update newstoptimes based on `update_freq(all_tripids)`_
>>> **}**
>>
>> _5) write object_
>> **}**
>
> _6) future.apply for all shapeids_
>
>  **return(output)**
> **}**

##### `mod_updates.R`
> **update_freq <- function(tripid,new_stoptimes){**
> _1) build 'id' vector all speed between stop sequences_
> _2) speed estimation_
> _3) update departure times_
> _4)  get freq info for that trip_
>> `# start frequencies functions`
>> **update_newstoptimes_freq(starttimes,freq_temp){**
>>> **update_departure_stoptimes(i,dt_list){**
>>> _5.1) update departure stoptimes_
>>> **return(dt_list)**
>> 
>>_5.2) function to update stoptimes of each departure (`update_departure_stoptimes`)_
>> _5.3) apply function and return the stop times of all departures from that period (`update_departure_stoptimes`)_
>>  **return(departure_stoptimes)**
>
> _6) update newstoptimes frequency_
> **return(new_stoptimes)**

the simple data frame behaves similarly
> **update_dt <- function(tripid,new_stoptimes){**
> _1) build 'id' vector all speed between stop sequences_
> _2) speed estimation_
> _3) update departure times_
> _4) recalculate time stamps_
> **return(new_stoptimes)**

**Comment by pedro-andrade-inpe** [comment]
This issue was already solved by https://github.com/ipeaGIT/gtfs2gps/pull/36, https://github.com/ipeaGIT/gtfs2gps/pull/48,  and  4f37503d2eccad70ddf975c55ef4259fcbd3012a.
