### ISSUE TITLE
merge two GTFS files

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [ipeaGIT/gtfs2gps#34]
Implement a function to merge two GTFS files. Be careful not to have duplicated IDs.

**Comment by rafapereirabr** [comment]
I've added a new function `merge_gtfs_feeds` to our package (commit 55eda53 ) . This is just a starting point, I believe we can improve the function from here. As it stands, the function does not check for duplicated IDs.

**Comment by pedro-andrade-inpe** [comment]
Nice! I only don´t know whether we should consider the question of GTFS files with and without frequencies. Could GTFS files of these two types be merged?

**Comment by rafapereirabr** [comment]
Merging two GTFS feeds of different types (detailed and frequency based) is not a problem per se. However, our core function `gtfs2gps` currently does not work well with mixed-type GTFS feeds. As it stands, the function assumes all data in a feed are of a single type. We know from the data of Rio de Janeiro, however, that a single GTFS feed might have some trips/routes organized in one way or another. I have created a separate issue for this. This should be fun to tackle.

**Comment by rafapereirabr** [comment]
Add `ERROR` if there are any `route_id` or `stop_ids` shared between different GTFS feeds

**Comment by rafapereirabr** [comment]
quick approach to check overlapping values
```
spo <- system.file("extdata/saopaulo.zip", package = "gtfs2gps")
poa <- system.file("extdata/poa.zip", package = "gtfs2gps")
gtfs_list <- list(spo, poa)

# read all feeds
all_feeds <- lapply(gtfs_list, read_gtfs)


##### STOPS ----------------------

# extract stops from all GTFS feeds
stops <- sapply(all_feeds, "[", 'stops')

# extract stop ids
stop_ids <-  sapply(stops, "[[", 'stop_id')

# check inersection between ids
output_intersect <- Reduce(intersect, stop_ids)

# if there is any overlap
if( length(output_intersect) = 0){ 
  stops <- rbindlist(stops, fill = T)
    }



##### AGENCY ----------------------
# extract stops from all GTFS feeds
agency <- sapply(all_feeds, "[", 'agency')

# extract stop ids
agency_ids <-  sapply(agency, "[[", 'agency_id')
```

**Comment by rafapereirabr** [comment]
then we need to update the trips, routes, shapes and stop `ids`:

```
for(i in 1:length(agency_ids)){
 stop_ids[i] <- sprintf("%s_%s", agency_ids[[i]], stop_ids[[i]])
 # route_ids[i] <- sprintf("%s_%s", agency_ids[[i]], route_ids[[i]])
 # trip_ids[i] <- sprintf("%s_%s", agency_ids[[i]], trip_ids[[i]])
 # ...
}
```
