### ISSUE TITLE
spatial resolution as an argument

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/gtfs2gps#38]
I'm noticing the processing time is taking a long time and the output is rather large. Ideally, we would like to include a `spatial resolution` argument to `gtfs2gps_single_dt.R`. Using lower spatial resolutions (say 500 meters or 1Km) could make the function more efficient at the expense of spatial detail, but some people might be fine with this trade-off.

However, I don't know whether it would be possible to include a spatial resolution argument to our 
 `gtfs2gps_single_dt.R` as it stands. What would happen if we used a spatial resolution of say 1Km but there is a pair of sequential stops that are  closer than that?

I just wanted to leave this issue registered here, but we can try do address it latter on after we have a robust version of the package running.

**Comment by pedro-andrade-inpe** [comment]
The algorithm of `sf::st_segmentize()` does not remove the original points, it only adds intermediate points whenever needed. If we use a spatial resolution of 1km possibly the output will be the same as the input, as every two consecultive points in GTFS data almost always have distance less than this resolution.

**Comment by rafapereirabr** [comment]
solved
