### ISSUE TITLE
strange bug when running check

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [ipeaGIT/gtfs2gps#39]
There is a strange error when running check. For poa data, ID "R10-2", two points are not being created. When only the tests are run it works perfectly. See the figure below. The only two missing points become more than a hundred points (in these two locations), as gtfs stores all the trips individually.

<img width="519" alt="gtfs2gps-issue" src="https://user-images.githubusercontent.com/8777631/67322420-56a83e00-f4e7-11e9-9394-7e7b5227a0b8.png">

**Comment by pedro-andrade-inpe** [comment]
This problem occurs in `sf::st_segmentize()`. "R10-2" has 472 points. In the tests,  `sf::st_segmentize()` returns 2026 points, while in check it returns 2024 points. @rafapereirabr, do you think it is important to focus on this issue for our first release?

**Comment by rafapereirabr** [comment]
Hi Pedro. I didn't quite understood the cause of the error but it does not seem to be a critical error. Does it?

**Comment by pedro-andrade-inpe** [comment]
It is not critical. Looks like it is an error in sf package or in the libs it uses, which is quite difficult to be reported as it occurs only within check.

**Comment by rafapereirabr** [comment]
Ok. In such a case, we can leave the issue open but this shouldn't really get much of our attention for now

**Comment by rafapereirabr** [comment]
Possibly a related problem. The output of  `gtfs2gps` is different when we run is locally or in CMD check.
For this snippet of code below for example, `my_dim` is 303851 locally, but CMD check returns 386708. Any idea why this happens?


```
    poa_gps <- read_gtfs(poa) %>%
      filter_week_days() %>%
      gtfs2gps(parallel = F, progress = F)
    
    my_dim <- dim(poa_gps)[1]
```

**Comment by pedro-andrade-inpe** [comment]
Yes, it is the same problem above. That's why we have tests like this:
https://github.com/ipeaGIT/gtfs2gps/blob/master/tests/testthat/test_gtfs2gps.R#L74

**Comment by rafapereirabr** [comment]
Do you know what causes this different problem? Why does the function gives different outputs locally and on CMD ? I couldn't find any info on this

**Comment by rafapereirabr** [comment]
On a side note, the important thing here is that the package is consistent in local machines, so this isn't a major problem and I believe we can proceed with CRAN submission. What do you think?
