### ISSUE TITLE
Suggestions for gtfs2gps_dt_single()

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [ipeaGIT/gtfs2gps#45]
I have two suggestions for `gtfs2gps_dt_single()`:

1) Rename it to simply `gtfs2gps()`, as we now will have only one function.
2) Remove the argument `week_days`. It might be interesting in order to work with large data to allow the user to execute this kind of function before running `gtfs2gps()` and save it separately. We could for instance have a progress bar for this and other filter functions as well.

**Comment by pedro-andrade-inpe** [comment]
@rafapereirabr, do you agree with these changes?

**Comment by rafapereirabr** [comment]
I like changing the function name to `gtfs2gps()`. Regarding the `week_days` argument, I think it makes sense to make this option available because service levels vary dramatically between weekdays and weekends. If we remove this argument, than our emission estimates latter on will affected by this info. What do you think?

**Comment by pedro-andrade-inpe** [comment]
I only do not like having an argument that simply calls a function that already belongs to the package, meaning that there are two ways of doing the same task. What do you think about allowing the first argument of `gtfs2gps()`  to be a GTFS list with `data.tables` (in addition to a file name). The user could then do something as follows:

```R
result <- read_gtfs("myfile.zip") %>%
    filter_week_days() %>%
    gtfs2gps() 
 ```

**Comment by rafapereirabr** [comment]
That would be fine. This would require changing the type of the input passed to `gtfs2gps()`. As it stands, the input is a zipped GTFS file (`"myfile.zip"`). We would only need to change this to a GTFS list with data.tables (the output from `read_gtfs()`
