### ISSUE TITLE
Simplify update_freq()?

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [ipeaGIT/gtfs2gps#46]
@Joaobazzo, @rafapereirabr , is it possible to simplify `update_freq()` to use `update_dt()` or am I missing something? The idea would be to have a code as follows:

```R
update_freq <- function(tripid, new_stoptimes, gtfs_data){
  new_stoptimes <- update_dt(tripid, new_stoptimes, gtfs_data) # several lines become one

  #  Get freq info for that trip
  # tripid <- "148L-10-0"
  freq_temp <- subset(gtfs_data$frequencies, trip_id== tripid)
```

**Comment by rafapereirabr** [comment]
Hi Pedro. I'll be out of office for few days so it's better for you and Joao to decide on this without me so I don't hold back the progress

**Comment by Joaobazzo** [comment]
I think it can work @pedro-andrade-inpe .

I will be making few tests but looks like we can verify the gtfs
data type inside the `update_single` function
That's for the idea!

``` r
update_single <- function(tripid, new_stoptimes, gtfs_data){
  #' Update new_stoptimes
  new_stoptimes <- update_dt(tripid, new_stoptimes, gtfs_data)
  #
  if(test_gtfs_freq(gtfs_data) == "frequency"){ 
  # Frequency procedure
  #
        return(new_stoptimes)
    }
    new_stoptimes <- lapply(starttimes,update_newstoptimes,freq_temp)%>% data.table::rbindlist()
    #departure_stoptimes <- update_newstoptimes_freq(starttime)
    
    return(new_stoptimes)
  }
}
```

<sup>Created on 2019-11-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Joaobazzo** [comment]
Hi @pedro-andrade-inpe , I've just updated `mod_updates.R` script with your suggestion. Let me know if it's working on your tests as well.
