### ISSUE TITLE
warning and parallel execution of gtfs2gps

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [ipeaGIT/gtfs2gps#55]
When running `gtfs2gps()` in parallel, all warnings related to inconsistencies in the data are surpressed. Maybe we could have a log file to store them.

**Comment by rafapereirabr** [comment]
@Joaobazzo I think you have somehow already implemented a solution to this in the code of our emissions project. right ?

**Comment by pedro-andrade-inpe** [comment]
Pakcage `future` is capturing warnings properly.

```R
library(gtfs2gps)
library(data.table)

gtfs_zip <- system.file("extdata/fortaleza.zip", package="gtfs2gps" )
gtfs_dt <- gtfs2gps::read_gtfs(gtfs_zip)
gtfs_filtered <- gtfs2gps::filter_day_period(gtfs_dt, period_start = "07:00:", period_end = "07:59")
gps_before <- gtfs2gps::gtfs2gps(gtfs_filtered, spatial_resolution = 15, plan = TRUE)
```
