### ISSUE TITLE
Parallelization using all CPUs

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/gtfs2gps#62]
We have two tasks that use parallel computing, (1) `data.table` some operations including `fwrite` and `fread`, and (2) the processing of multiple `shape_ids` in `gtfs2gps`.

The `data.table` operations are already running with all CPUs available because we have set
```
.onLoad = function(lib, pkg) {
  # Use GForce Optimisations in data.table operations
  # details > https://jangorecki.gitlab.io/data.cube/library/data.table/html/datatable-optimize.html
  options(datatable.optimize = Inf) # nocov
  
  # set number of threads used in data.table 
  data.table::setDTthreads(percent = 100) # nocov
}
```

I was wondering if we could also set the `core` argument of `gtfs2gps`  default to use all logical CPUs available.

`core = getDTthreads(verbose)`

What do you think?

**Comment by pedro-andrade-inpe** [comment]
@rafapereirabr, I prefer to have as default the number of cores minus one (or one if there is only one), to avoid freezing the computer screen.

**Comment by rafapereirabr** [comment]
Good idea. I've just implemented it. I'm pushing to the repo right away
