### ISSUE TITLE
Create Hex sticker

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/gtfs2gps#75]
It would be nice to have a hex sticker for the package. I've created a draft proposal so we can have a starting point to discuss.  Here is draft version 1:

<img src="https://github.com/ipeaGIT/gtfs2gps/raw/master/man/figures/gtfs2gps_logo.png" width="160">

I know, it's not great. I wanted to convey the output in `data.table` format but I recognized it should also have an element related to public transport that is still missing from the logo. Perhaps the acronym **gtfs** in the package name would suffice, or perhaps you have other suggestions.

The logo was created using the script `./man/figures/gtfs2gps_hexsticker.R`, so please feel free to tweak the code and make your suggestions.

**Comment by rafapereirabr** [comment]
Perhaps something more like the `readr` sticker: 

<img src="https://github.com/rstudio/hex-stickers/raw/master/PNG/readr.png" width="160">

**Comment by rafapereirabr** [comment]
How about something like this? The zip here should be a direct reference to gtfs zipped files and, with some imagination, the zipper lines make a reference to public transport routes.

<img width="286" alt="gtfs2gps" src="https://user-images.githubusercontent.com/7448421/92186195-62190500-ee2c-11ea-9281-0503475d8a5b.PNG">

**Comment by rafapereirabr** [comment]
This is the latest version we have, thanks to the great contribution from @mvpsaraiva . I really like the sticker, but I would probably go with a ligher color. Thoughts?

![Picture2](https://user-images.githubusercontent.com/7448421/110770190-caabc900-8237-11eb-8c90-bb4e4123acda.png)

**Comment by pedro-andrade-inpe** [comment]
I like it. My only suggestion would be verify whether it would be better to change the colors of the transportation facilities. White has more contrast with blue than black. See two suggestions created in paintbrush.
![image](https://user-images.githubusercontent.com/8777631/110783770-9fc97100-8247-11eb-82fe-aea8854a9c9f.png)

**Comment by mvpsaraiva** [comment]
Looking at it now, after a couple of months, I also think it's 'too heavy'. Both the colours and the thick hex border. I like @pedro-andrade-inpe suggestion of white transit cars as well.

**Comment by mvpsaraiva** [comment]
Morning procrastination results:

![gtfs2gps hex v3](https://user-images.githubusercontent.com/7387691/110785770-16676e00-824a-11eb-9fee-06563d923339.png)
![gtfs2gps hex v4](https://user-images.githubusercontent.com/7387691/110785782-19faf500-824a-11eb-9465-90c4417bf126.png)

I'm not sure about the blue or black border...

**Comment by pedro-andrade-inpe** [comment]
Nice! The blue border looks better for me.

**Comment by rafapereirabr** [comment]
I like the new one with white vehicles and blue border as well. If we all agree with this, I would kindly ask @mvpsaraiva to submit a pull request including the hex sticker to the repo `./man/figures/`  in .png format and closing this issue

**Comment by mvpsaraiva** [comment]
> I like the new one with white vehicles and blue border as well. If we all agree with this, I would kindly ask @mvpsaraiva to submit a pull request including the hex sticker to the repo `./man/figures/` in .png format and closing this issue

Done!

**Comment by rafapereirabr** [comment]
Obrigado, Marcus!
