### ISSUE TITLE
filter by agency_id

### ISSUE THREAD

**Issue by ahermanski** [ipeaGIT/gtfs2gps#76]
Similiar to how 
```r
filter_by_shape_id
```
 works, could you implement a way to filter by agency_id? Obviously there's a roundabout way to get all the shape_ids for an agency, but that can lead to extremely long vectors, as I've experienced with the Berlin gtfs, where there's over 3000 ids for the agency's I was interested in.

**Comment by pedro-andrade-inpe** [comment]
@ahermanski, I've just implemented this function, but I do not have a real GTFS file with two agencies to test it properly. It would be nice if you could test with your data and give us a feedback.

**Comment by ahermanski** [comment]
Thanks for adding the function. Just took a quick look at my Berlin data, and it seems to work as intended. When I find the time, I'll take a closer look.

**Comment by pedro-andrade-inpe** [comment]
Great.
