### ISSUE TITLE
Filtering for time of day

### ISSUE THREAD

**Issue by ahermanski** [ipeaGIT/gtfs2gps#79]
I'm unsure if this isn't the same as what is mentioned in #44 , but an option to filter for a specific period during the day could be interesting.

**Comment by rafapereirabr** [comment]
Thanks for the suggestion. I've added a new function `filter_day_period.R` that we'll take as a starting point to improve the package. 

This issue has been raised before in issue #16 , so I'm closing this one. We can continue the conversation from there.
