### ISSUE TITLE
Package not passing tests

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/gtfs2gps#82]
I know, my last commit #a902a00 broke the core function of the package. Sorry :] 

It seems to be related to this change I did between lines 80 and 91, but this needs to be investigated further. 

```
    # # old (slower) version
    # new_shape <- subset(shapes_sf, shape_id == shapeid) %>%
    #   sf::st_segmentize(spatial_resolution) %>%
    #   sf::st_cast("LINESTRING") %>%
    #   sf::st_cast("POINT", warn = FALSE)  %>% 
    #   sf::st_sf()

    # new faster verion using sfheaders
    new_shape <- subset(shapes_sf, shape_id == shapeid) %>%
      sf::st_segmentize(spatial_resolution) %>%
      sfheaders::sf_to_df(fill = T) %>%
      sfheaders::sf_point( x = "x", y="y", keep = T)

```

**Comment by rafapereirabr** [comment]
@Joaobazzo , it seems the error is happening 97 and 105 of `mod_updates.R`
```
    # building id' vector
    #
    # lim0: 'id' in which stop_times intervals STARTS
    # lim1: 'id' in which stop_times intervals ENDS
    # lim_len: length of each constant speed interval
    lim0 <- which(is.na(new_stoptimes$stop_sequence) == FALSE)
    lim1 <- c(tail(lim0,-1) - 1 ,nrow(new_stoptimes)) 
    lim_len <- lim1 - lim0 + 1
    new_stoptimes$speed_sequence <- rep(1:length(lim0),lim_len) # speed_sequence
```
When I manually run the poa data with `shapeid = "A141-1"` and `tripid = "A141-1@1#30"`, I get the following error:

> Error in set(x, j = name, value = value) : 
>  Supplied 530 items to be assigned to 540 items of column 'speed_sequence'. If you wish to > 'recycle' the RHS please use rep() to make this intent clear to readers of your code.

**Comment by rafapereirabr** [comment]
Hi Pedro. Thanks for the Pull request. The PR seems to have created another problem somewherelse. The package is not passing the tests in `test_gtfs2gps.R`.

The code below, for example, returns a `data.frame` with 0 rows.

```
    poa <- system.file("extdata/poa.zip", package="gtfs2gps")

    poa_gps <- read_gtfs(poa) %>%
      filter_week_days() %>%
      gtfs2gps()

```

**Comment by Joaobazzo** [comment]
Estranho. Aqui rodou, mas não sei se fiz da forma correta. Se tiver tempo me mostre amanha

```r
==> Testing R file using 'testthat'

Loading gtfs2gps
v |  OK F W S | Context
v |  19       | test_gtfs2gps [31.2 s]=======================================================================

== Results ============================================================================
Duration: 31.2 s

OK:       19
Failed:   0
Warnings: 0
Skipped:  0

Test complete
```
