### ISSUE TITLE
tests fail in R CMD check but pass in devtools::test()

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/gtfs2gps#84]
Not sure why this is happening. Perhaps [this](https://github.com/rstudio/renv/issues/162) could gives us a clue to the solution. In the `gtfs2gps.Rcheck\tests_i386\testthat.Rout.fail` there is this error message: `DLL 'sf' not found: maybe not installed for this architecture?`

**Comment by pedro-andrade-inpe** [comment]
@rafapereirabr, I've just run R CMD check in a Windows prompt with a built version of the package and it is working fine, except by a small warning that I'm trying to solve. How did you run R CMD check?

**Comment by rafapereirabr** [comment]
I'll run another CMD when I get home.

In the meantime, you can check the buil tests on Travis [https://travis-ci.org/ipeaGIT/gtfs2gps](https://travis-ci.org/ipeaGIT/gtfs2gps)

**Comment by rafapereirabr** [comment]
Hi Pedro. I've just run a CMD check got no notes, errors nor warnings! I guess we can close this issue now. Could you please go ahead and submit the package to CRAN?
