### ISSUE TITLE
improve time filter in `filter_day_period`

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/gtfs2gps#89]
As of today, the function `filter_day_period.R` only works with frequency-based GTFS feeds when the `start_period - end_period` is longer than 1 hour, 2 hours, 3 hours etc. If `start_period - end_period` is '01:20', for example, the function will only keep the trips sections within the first full hour.

One way to solve this, would be to round down `start_period` and round up  `end_period` to full hours. It seems the best approach to do this would be to convert `x_period`  and `departure_time` to numeric and run all time operations based on numeric vectors. We would only convert `departure_time` back to `ITime()` in the final output of the functions. 

ps. This apporach migh improve the package efficiency because `as.ITime()` conversion takes quite some time.

**Comment by pedro-andrade-inpe** [comment]
Analysing Sao Paulo data, all the frequencies start in rounded hours and last 59 minutes. That's why the queries above do not work:

```R
sp <- read_gtfs(system.file("extdata/saopaulo.zip", package = "gtfs2gps"))
unique(sp$frequencies$end_time - sp$frequencies$start_time)
[1] "00:59:00"
sort(unique(sp$frequencies$start_time))
 [1] "00:00:00" "01:00:00" "02:00:00" "03:00:00" "04:00:00" "05:00:00" "06:00:00" "07:00:00"
 [9] "08:00:00" "09:00:00" "10:00:00" "11:00:00" "12:00:00" "13:00:00" "14:00:00" "15:00:00"
[17] "16:00:00" "17:00:00" "18:00:00" "19:00:00" "20:00:00" "21:00:00" "22:00:00" "23:00:00"
```

Removing the `if` in the source code that prevented running with minutes, we have:

```R
period_start = "10:00"
period_end = "10:59"

frequencies <- sp$frequencies[ data.table::as.ITime(start_time) >= data.table::as.ITime(period_start) & data.table::as.ITime(end_time) <= data.table::as.ITime(period_end) ] 

frequencies
```

```
         trip_id start_time end_time headway_secs
   1:  1012-10-0   10:00:00 10:59:00          480
   2:  1012-10-1   10:00:00 10:59:00          480
   3:  1015-10-0   10:00:00 10:59:00         1800
   4:  1016-10-0   10:00:00 10:59:00          360
   5:  1016-10-1   10:00:00 10:59:00          360
  ---                                            
1895: METRÔ L3-1   10:00:00 10:59:00          180
1896: METRÔ L4-0   10:00:00 10:59:00          180
1897: METRÔ L4-1   10:00:00 10:59:00          180
1898: METRÔ L5-0   10:00:00 10:59:00          480
1899: METRÔ L5-1   10:00:00 10:59:00          480
```

Additionally, setting some times manually also works properly:

```R
sp$frequencies$start_time[1] <- data.table::as.ITime("09:59:00")
sp$frequencies$start_time[2] <- data.table::as.ITime("09:59:00")
sp$frequencies$start_time[3] <- data.table::as.ITime("10:00:00")
sp$frequencies$start_time[4] <- data.table::as.ITime("10:00:00")
sp$frequencies$start_time[5] <- data.table::as.ITime("10:01:00")
sp$frequencies$start_time[6] <- data.table::as.ITime("10:01:00")

sp$frequencies$end_time[1] <- data.table::as.ITime("10:19:00")
sp$frequencies$end_time[2] <- data.table::as.ITime("10:20:00")
sp$frequencies$end_time[3] <- data.table::as.ITime("10:19:00")
sp$frequencies$end_time[4] <- data.table::as.ITime("10:20:00")
sp$frequencies$end_time[5] <- data.table::as.ITime("10:19:00")
sp$frequencies$end_time[6] <- data.table::as.ITime("10:20:00")

sp_f <- filter_day_period(sp, period_start = "10:00", period_end = "10:20")
sp_f$frequencies
```

```
     trip_id start_time end_time headway_secs
1: 1012-10-0   10:00:00 10:19:00          600
2: 1012-10-0   10:00:00 10:20:00          480
3: 1012-10-0   10:01:00 10:19:00          480
4: 1012-10-0   10:01:00 10:20:00          420
```

@rafapereirabr, what do you think? @Joaobazzo do you have some data with more heterogeneous `start_time` and `end_time` in `frequencies`?

**Comment by rafapereirabr** [comment]
This looks like a really simple and effective solution! I guess this is now just a matter of testing with other GTFS feeds. We might need to dig a bit into the feeds stored at [Transiland](https://www.transit.land/feeds), unless Joao knows already a couple feeds that we could use for this specific test
