### ISSUE TITLE
Removing lwgeom dependency

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/gtfs2gps#92]
I've noticed we are not usig `lwgeom::st_make_valid` anywhere in the package. I guess it's Ok to remove lwgeom dependency, right? or did you guys have some use in mind?

**Comment by pedro-andrade-inpe** [comment]
`sf::st_length` requires lwgeom for lat/long data:

https://github.com/r-spatial/sf/blob/1831930867505098571c6ade24344babd9ea6bfd/R/geom.R#L97

As we use lat/long data in the tests, it is necessary to have lwgeom at least in suggests. But maybe as gtfs data usually uses lat/long data we could keep lwgeom as Imports. @rafapereirabr, what do you prefer?

**Comment by rafapereirabr** [comment]
Ok. We should probably keep in imports then. thanks for clarifying this to me!
